" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'dense-analysis/ale'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'saltstack/salt-vim'
" Plug 'dracula/vim', { 'as': 'dracula' }

" All of your Plugins must be added before the following line
call plug#end()             " required
filetype plugin indent on   " required
let g:plug_window = 'enew'  " Prevent vertical split

set background=dark
set t_Co=256            " Enable 256 colors, must appear before any syntax and color settings
set modeline
set tabstop=2
set shiftwidth=2        " Soft space = 2
set expandtab
set wildchar=9          " Tab as completion character
set virtualedit=block
set clipboard+=unnamed	" Yanks go on clipboard instead.
set showmatch           " Show matching braces.
set wrap                " Line wrapping on by default
set linebreak
set history=50          " Keep track of last commands
set number ruler      	" Show line numbers
set incsearch 	       	" Incremental searching on
set hlsearch            " Highlight all matches
set smartcase
set cursorline
set selectmode=key
set showtabline=2       " Show always for console version
set laststatus=2        " Always show the statusline
set wildmenu            " Menu on statusbar for command autocomplete
set encoding=utf8       " Default to UTF-8 encoding
set fileencoding=utf8
set viminfofile=~/.vim/viminfo
" Enable visible whitespace
" set listchars=tab:»·,trail:·,precedes:<,extends:>
" set listchars=tab:>.,trail:.,extends:#,nbsp:.
" set list

syntax on               " turn on syntax highlighting
set nocompatible
autocmd BufNewFile,BufRead *.json set ft=javascript

colorscheme molokai
let g:molokai_original = 1
let g:rehash256 = 1

" colorscheme dracula
" let g:dracula_colorterm = 1

if exists('$TMUX')
  set term=screen-256color
endif

let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_sign_column_always = 1

let g:airline_theme='powerlineish'
let g:airline_powerline_fonts=1
let g:airline#extensions#ale#enabled = 1
